version: 3
services:
  web:
    image: nginx
    environment:
      - NODE_ENV: production
      - SECRET_KEY: mysecretkey
  db:
    image: postgres
    environment:
      - POSTGRES_DB: mydb
      - POSTGRES_USER: user
      - POSTGRES_PASSWORD: password
